# -*- coding: utf-8 -*-
"""creating DataFrame from in-memory data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAisSy8qu9JpVgncy-DBJG7A7jNySL-t
"""

import pandas as pd
import numpy as np

name=pd.Series(['babu','raju','gopi','srinu'],name='Name')
hp=pd.Series([45,60,80],name='HP')
leg=pd.Series([False,True,False,True],name='Legendary')
df1=pd.concat([name,hp,leg],axis=1)
df1

data={'Name':['a','b','c'],'HP':[1,2,3],'Legendary':[False,True,True]}
df1=pd.DataFrame(data)
df1

data=[['a',1,False],['b',2,True],['c',3,True]]
df1=pd.DataFrame(data)
df1

data=np.array([['a',1,False],['b',2,True],['c',3,True]])
df1=pd.DataFrame(data)
df1