# -*- coding: utf-8 -*-
"""Data Aggregation by Pandas GroupBy object.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHar6YmXMonFg4NAcwGe89hqeeLr5PhM
"""

import pandas as pd
import numpy as np
import seaborn as sns

tips=pd.read_excel('/content/tips.xlsx')
tips

msum=fsum=0
for i in range(len(tips)):
  if tips.loc[i].sex=='Male':
    msum+=tips.loc[i].total_bill
  else:
    fsum+=tips.loc[i].total_bill
print('male:',round(msum,2))

tip=0
for i in range(len(tips)):
    tip+=tips.loc[i].tip
print(tip)

tips['tip'].sum().round(2)

tips.loc[tips.sex=='Male'].total_bill.sum().round(2)

grp_by_day=tips.groupby('day')

for day,group in grp_by_day:
  print(day)
  print(group)

grp_by_day.ngroups

grp_by_day.size()

grp_by_day.first()

grp_by_day.last()

grp_by_day.nth(5)

grp_by_day.groups

grp_by_day.total_bill.sum()

grp_by_day[['total_bill','tip']].sum()

grp_by_day[['total_bill','tip']].agg(['sum','mean'])

grp_by_day[['total_bill','tip']].agg({'total_bill':'sum','tip':'mean'})

grp_by_day.get_group('Sun')