# -*- coding: utf-8 -*-
"""Data Frame Diagnostic properties&Methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjG6caqZuHSAJBioS8kFWvrOyCrMFl5d

Access columns and apply properties&functios
"""

import pandas as pd
df=pd.read_excel("/content/pokemon_data.xlsx")
print(df)

df.columns

df['Name']



df.HP.sum()

df.Name

df.HP.agg(['sum','mean'])

df.HP.unique()

df['Type 1'].unique()

df['Type 2'].unique()

df['Type 2'].unique()[0]

"""Row/Column Indexing"""

df[['Name','HP']]

df['Type 2'].nunique()

df1=df[['Name','HP']]
df1

df[['Name','HP']].HP.sum()

df[0:5]

df[-6:-1]

df[0:]

df[:1]

"""Row and column indexiing loc[],iloc[]"""

df.loc

df.loc[0:5,['Name','HP']]

df.loc[0:5,['Name']]

df.loc[0:5,'Name']

df.loc[0:5]

df.loc[[0,5,12]]

df.loc[0,'Name']

df.loc[[0]]

df.loc[0]

df.loc[:]

df.loc[:,'Name':'HP']

df.iloc[:,1:4]

df.iloc[[2]]

df.iloc[2]

df.iloc[:5,1:4]

df.iloc[0:5,3]

df.iloc[:5]

df.loc[:5,'Name']

"""Other filtering methods"""

df.nlargest(5,'Attack')

df.nlargest(5,'Attack').reset_index()

df.nsmallest(10,'HP')

df.nsmallest(10,'HP').reset_index()

"""Boolean Indexing"""

df

df.HP>75

df.loc[df.HP>75]

df.loc[df.HP>75,'Name':'HP']

df.loc[df.HP>75,'Name']

df.loc[df.Attack>75,'Name':'HP']

df.loc[(df.HP>75)&(df['Type 1']=='Grass'),'Name':'HP'].reset_index()

df.iloc[0:5:10]

df1=pd.read_json('/content/data.json')
df1

df2=pd.read_table("/content/pokemon_data.txt")
df2

df3=pd.read_csv("/content/pokemon_data.csv")
df3

