# -*- coding: utf-8 -*-
"""Handling NULL values in pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PPBZs35BMrfTIvZctlMUHkVDK7JtfPL
"""

import pandas as pd
import numpy as np

df1=pd.read_excel('/content/tips.xlsx')
df1

df=pd.DataFrame([[4,3,2,1],[10,20,30],[10,20],[10]],columns=['C1','C2','C3','C4'])
df

df.isnull()

df.isnull().sum()

df.isnull().sum(axis=0)

df.isnull().sum(axis=1)

df.notnull()

df.dropna()

df.dropna(how='any')

df.dropna(how='all')

df.dropna(thresh=2)

df.dropna(thresh=3)

df.fillna(method='ffill')

df.fillna(method='bfill')

df.fillna(method='ffill',limit=1)

df.fillna(0)

df.fillna(df.max())

df.fillna(df.mean())

pk=pd.read_excel('/content/pokemon_data.xlsx')
pk

pk.isnull()

pk.isnull().sum()

pk.isnull().sum(axis=1)

pk.notnull()

pk.dropna()

pk.dropna(how='all')

pk.dropna(thresh=12)

pk.nlargest(10,'Generation')