# -*- coding: utf-8 -*-
"""Merge Join and Concat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3tw9t-zcg1QvR7Up4i587n7E8f60d5V
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

"""Merge"""

df1=pd.DataFrame([['Alpha',10],['Beta',20],['Gamma',30]],columns=['Name','Dno'])
df1

df2=pd.DataFrame([[10,'moon'],[20,'venus'],[40,'mars']],columns=['Dno','Dloc'])
df2

pd.merge(df1,df2)

df1.merge(df2,indicator=True)

df1.merge(df2,how='left')

df1.merge(df2,how='right')

df1.merge(df2,how='outer')

df1.merge(df2,how='cross')

"""Join"""

df1=pd.DataFrame([['alice',25],['bob',30],['charlie',35]],columns=['Name','Age'])
df1

df2=pd.DataFrame([['laptop',2000],['phone',750],['tablet',500]],columns=['purchase','cost'],index=[1,2,3])
df2

df1.join(df2)

df1.join(df2,how='inner')

df1.join(df2,how='right')

df1.join(df2,how='outer')

"""Concat

Vertical concatenation
"""

tips=sns.load_dataset('tips')
tips1=tips.iloc[:100]
tips2=tips.iloc[100:]

tips1

tips2

pd.concat([tips1,tips2])

"""Horizontal concatenation"""

tips1=tips.iloc[:,:3]
tips2=tips.iloc[:,3:]

tips1

tips2

pd.concat([tips1,tips2],axis=1)

"""PIVOT"""

df=pd.DataFrame([['R1','physics',85],['R1','maths',92],['R2','physics',78],['R2','maths',88]],columns=['nmae','subject','marks'])
df

df.pivot(index='nmae',columns='subject',values='marks')

df=pd.DataFrame([['R1','physics',85],['R1','physics',78],['R1','maths',92],['R1','maths',97],['R2','physics',78],['R2','physics',88],['R2','maths',88],['R2','maths',92]],columns=['nmae','subject','marks'])
df

df.pivot_table(index='nmae',columns='subject',values='marks')

df.pivot_table(index='nmae',columns='subject',values='marks',aggfunc='sum')