# -*- coding: utf-8 -*-
"""Multi-level GroupBy indexing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmM6p2tVz-sW0kcTUoRuyaz9Z05qTwD8
"""

import pandas as pd
import numpy as np

tips=pd.read_excel('/content/tips.xlsx')
tips

grp_by_day_time=tips.groupby(['day','time'])

for (day,time),grp in grp_by_day_time:
  print(day,'--',time)
  print(grp)

grp_by_day_time.get_group(('Sun','Dinner'))

grp_by_day_time.total_bill.sum()

grp_by_day_time[['total_bill','size']].sum()

grp_by_day_time.size()

grp_by_day_time.first()

grp_by_day_time.last()

grp_by_day_time.nth(5)

grp_by_day_time.groups

grp_by_day_time[['total_bill','size']].agg({'total_bill':'sum','size':'mean'})

grp_by_day_time[['total_bill','tip']].agg(['sum','mean'])

grp_by_day_time['tip'].sum()