# -*- coding: utf-8 -*-
"""Other filtering methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wr9z_5B6iqKvIVv_WiURceNaMa7q9p6
"""

import pandas as pd
df=pd.read_csv('/content/pokemon_data.csv')

df.nlargest(5,'HP')

df.nsmallest(5,'HP')

df.sample(n=10)

df.sample(n=10).reset_index()

df.sample(frac=0.8)

df.query('HP>200')[['Name','HP']]

df.query('`Type 1`=="Grass"')

df.query('`Type 1`=="Grass" and HP>100')

df.select_dtypes(include=[int])

df.select_dtypes(include=[int,bool])

df.select_dtypes(exclude=[int])

df.select_dtypes(exclude=[int,bool])