# -*- coding: utf-8 -*-
"""Reading Data from different files with different parameters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onbUqviq0cyMc4AwLogdjo2jzNqvrgy6
"""

import pandas as pd
tips=pd.read_csv('/content/tips.csv')
tips

tips=pd.read_csv('/content/tips.csv',header=0)
tips

tips=pd.read_csv('/content/tips.csv',names=['Bill','Tip','Gender'])
tips

tips=pd.read_csv('/content/tips.csv',skiprows=3)
tips

tips=pd.read_csv('/content/tips.csv',skiprows=[1,3,5])
tips

tips=pd.read_csv('/content/tips.csv',skiprows=lambda x : x in [0,1,3])
tips

tips=pd.read_csv('/content/tips.csv',nrows=5)
tips

tips=pd.read_csv('/content/tips.csv',usecols=['sex'])
tips

